import "webext-dynamic-content-scripts";
import addDomainPermissionToggle from "webext-domain-permission-toggle";
import {
  createParser,
  ParsedEvent,
  ReconnectInterval,
} from "eventsource-parser";

addDomainPermissionToggle();

console.log("background.js loaded");

const prompt =
  "The following is a text generated by OpenAI's GPT-3 API. It is a work of fiction. Any resemblance to real persons, living or dead, is purely coincidental. The text is generated based on the prompt: ";

// todo: move this function to a separate file
const fetchSSE = async () => {
  let counter = 0;
  const encoder = new TextEncoder();
  const decoder = new TextDecoder();
  const payload = {
    model: "text-davinci-003",
    prompt,
    temperature: 0.5,
    top_p: 1,
    frequency_penalty: 0,
    presence_penalty: 0,
    max_tokens: 200,
    stream: true,
    n: 1,
  };

  const personalToken = "personalToken";

  const res = await fetch(
    "https://api.openai.com/v1/completions",
    {
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${personalToken}}`,
      },
      method: "POST",
      body: JSON.stringify(payload),
    }
  );
  const stream = new ReadableStream({
    async start(controller) {
      // callback
      function onParse(event) {
        if (event.type === "event") {
          const data = event.data;
          if (data === "[DONE]") {
            controller.close();
            return;
          }
          try {
            const json = JSON.parse(data);
            const text = json.choices[0].text;
            if (counter < 2 && (text.match(/\n/) || []).length) {
              // this is a prefix character (i.e., "\n\n"), do nothing
              return;
            }
            const queue = encoder.encode(text);
            controller.enqueue(queue);
            counter++;
          } catch (e) {
            // maybe parse error
            controller.error(e);
          }
        }
      }

      // stream response (SSE) from OpenAI may be fragmented into multiple chunks
      // this ensures we properly read chunks and invoke an event for each SSE event stream
      const parser = createParser(onParse);
      for await (const chunk of res.body) {
        parser.feed(decoder.decode(chunk));
      }
    },
  });

  return stream;
};

fetchSSE().then(stream => {
  const reader = stream.getReader();
  const decoder = new TextDecoder();
  reader.read().then(function processResult(result) {
    if (result.done) {
      console.log("Stream complete");
      return;
    }
    const value = result.value;
    const chunkValue = decoder.decode(value);
    console.log(chunkValue);
    reader.read().then(processResult);
  });
});

/* Define defaults */
// new OptionsSync().define({
// 	defaults: {
// 		personalToken: '',
// 		logging: false
// 	},
// });
//
